PetsWebsite/PetsWebsite/Models/ViewModels/CreateClinicViewModel.cs
namespace PetsWebsite.Models.ViewModels
{
    public class CreateClinicViewModel
    {
        public string ClinicName { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public string? Describe { get; set; }
        public string Emergency { get; set; }
        public string? Service { get; set; }
        public string? ClinicMap { get; set; }
    }
}

PetsWebsite/PetsWebsite/Controllers/OwnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetsWebsite.Extensions;
using PetsWebsite.Models;
using PetsWebsite.Models.ViewModels;

namespace PetsWebsite.Controllers
{
    public class OwnerController : Controller
    {
        private readonly PetsDBContext _dBContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly GoogleMapService _googleMapService;

        public OwnerController(PetsDBContext dBContext, IWebHostEnvironment webHostEnvironment, GoogleMapService googleMapService)
        {
            _dBContext = dBContext;
            _webHostEnvironment = webHostEnvironment;
            _googleMapService = googleMapService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        public IActionResult CreateRestaurant()
        {
            return View();
        }
        public IActionResult CreateClinic()
        {
            return View();
        }

        // 新增商品
        public bool NewProduct(ProductViewModel newProduct)
        {
            // 整理資料
            Product product = new Product();
            product.CategoryId = 1;
            product.CompanyId = User.GetId();
            product.ProductName = newProduct.ProductName.Trim();
            product.UnitPrice = newProduct.UnitPrice;
            product.UnitsInStock = newProduct.UnitsInStock;
            product.Describe = newProduct.Describe?.Trim();
            product.State = false;
            product.LaunchDate = DateTime.Now;
            product.Discount = newProduct.Discount;
            product.Species = newProduct.Species == "0" ? true : false;

            // 取出表單圖片及名稱
            var InputFile = HttpContext.Request.Form.Files[0]; // 在深層自動變數的地方
            var InputFilePath = "";
            if (InputFile == null)
            {
                product.PhotoPath = "product_Default";
            }
            else
            {
                // 儲存photo
                var UniqueId = Guid.NewGuid().ToString("D");
                var PhotoFormat = InputFile.FileName.Split(".")[1];
                product.PhotoPath = $"{product.CompanyId}_{UniqueId}.{PhotoFormat}";

                InputFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Product", product.PhotoPath);
                FileStream fs = new FileStream(InputFilePath, FileMode.Create);
                InputFile.CopyTo(fs); // 將圖片放入指定位置
                fs.Close();
            }
            _dBContext.Products.Add(product);
            _dBContext.SaveChanges();
            return true;
        }

        // 帶資料跳轉修改商品頁面
        [Route("Owner/EditProduct/{ProductId}")]
        public IActionResult EditProduct(int ProductId)
        {
            var query = _dBContext.Products.First(x => x.ProductId == ProductId);
            ProductViewModel product = new ProductViewModel();
            product.ProductId = query.ProductId;
            product.ProductName = query.ProductName;
            product.UnitPrice = query.UnitPrice;
            product.UnitsInStock = query.UnitsInStock;
            product.PhotoPath = query.PhotoPath;
            product.Describe = query.Describe;
            product.Species = query.Species == true? "0" : "1";
            return View(product);
        }

        // 儲存修改商品
        public bool SaveEditedProduct(Product editedProduct)
        {
            var query = _dBContext.Products.FirstOrDefault(p => p.ProductId == editedProduct.ProductId);
            editedProduct.CompanyId = User.GetId();

            // 判斷有無修改圖檔
            if (HttpContext.Request.Form.Files.Count != 0)
            {
                // 找出舊圖路徑
                var oldPhoto = _dBContext.Products.Where(p => p.ProductId == editedProduct.ProductId).Select(p => p.PhotoPath).Single();

                // 判斷是否為null
                if (!string.IsNullOrEmpty(oldPhoto))
                {
                    var oldPhotoPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Product", oldPhoto);
                    // 刪除舊圖
                    System.IO.File.Delete(oldPhotoPath);
                }

                // 找出圖檔
                var InputFile = HttpContext.Request.Form.Files[0];
                var InputFilePath = "";

                // 儲存photo
                var UniqueId = Guid.NewGuid().ToString("D");
                var PhotoFormat = InputFile.FileName.Split(".")[1];
                editedProduct.PhotoPath = $"{editedProduct.CompanyId}_{UniqueId}.{PhotoFormat}";

                InputFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Product", editedProduct.PhotoPath);
                FileStream fs = new FileStream(InputFilePath, FileMode.Create);
                InputFile.CopyTo(fs);
                fs.Close();

                // 儲存圖片
                query.PhotoPath = editedProduct.PhotoPath;
            }

            // 儲存資料
            query.ProductName = editedProduct.ProductName.Trim();
            query.UnitPrice = editedProduct.UnitPrice;
            query.Describe = editedProduct.Describe?.Trim();
            query.LaunchDate = DateTime.Now;
            try
            {
                _dBContext.SaveChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        // 刪除商品
        [Route("Owner/DeleteProduct/{ProductId}")]
        public bool DeleteProduct(int ProductId)
        {
            var query = _dBContext.Products.First(p => p.ProductId == ProductId);
            try
            {
                var OldPhoto = query.PhotoPath;
                _dBContext.Remove(query);
                _dBContext.SaveChanges();
                if (!string.IsNullOrEmpty(OldPhoto))
                {
                    var OldPhotoPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Product", OldPhoto);
                    System.IO.File.Delete(OldPhotoPath);
                }
            }
            catch(Exception)
            {
                return false;
            }
            return true;
        }

        public async Task<bool> NewRestaurant(Restaurant newRestaurant)
        {
            // 整理資料
            //newRestaurant.CategoryId = 2;
            newRestaurant.CompanyId = User.GetId();
            newRestaurant.RestaurantName = newRestaurant.RestaurantName.Trim();
            newRestaurant.Address = newRestaurant.Address.Trim();
            newRestaurant.Introduction = newRestaurant.Introduction?.Trim();
            newRestaurant.Reserve = newRestaurant.Reserve?.Trim();
            newRestaurant.BusyTime = newRestaurant.BusyTime?.Trim();
            newRestaurant.Phone = newRestaurant.Phone?.Trim();
            newRestaurant.State = false;

            //GoogleMapService googleMapService = new GoogleMapService();
            var result = _googleMapService.GetLatLngByAddr($"{newRestaurant.City}{newRestaurant.Region}{newRestaurant.Address}");
            newRestaurant.Latitude = Convert.ToDouble(result.lat);
            newRestaurant.Longitude = Convert.ToDouble(result.lng);

            // 取出圖片及名稱
            var InputFile = HttpContext.Request.Form.Files[0];
            var InputFilePath = "";
            if (InputFile == null)
            {
                newRestaurant.PhotoPath = "restaurant_Default";
            }
            else
            {
                // 儲存photo
                var UniqueId = Guid.NewGuid().ToString("D");
                var PhotoFormat = InputFile.FileName.Split(".")[1];
                newRestaurant.PhotoPath = $"{newRestaurant.CompanyId}_{UniqueId}.{PhotoFormat}";

                InputFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Restaurant", newRestaurant.PhotoPath);
                FileStream fs = new FileStream(InputFilePath, FileMode.Create);
                InputFile.CopyTo(fs);
            }
            _dBContext.Restaurants.Add(newRestaurant);
            _dBContext.SaveChanges();
            return true;
        }

        [Route("Owner/EditRestaurant/{RestaurantId}")]
        public IActionResult EditRestaurant(int RestaurantId)
        {
            var query = _dBContext.Restaurants.FirstOrDefault(r => r.RestaurantId == RestaurantId);

            ViewBag.editRestaurant = query;
            return View();
        }

        public async Task<IActionResult> SaveEditedRestaurant(Restaurant editedRestaurant)
        {
            var query = _dBContext.Restaurants.FirstOrDefault(r => r.RestaurantId == editedRestaurant.RestaurantId);
            editedRestaurant.CompanyId = User.GetId();

            if (HttpContext.Request.Form.Files.Count != 0)
            {
                var oldPhoto = _dBContext.Restaurants.Where(r => r.RestaurantId == editedRestaurant.RestaurantId).Select(r => r.PhotoPath).Single();

                if (!string.IsNullOrEmpty(oldPhoto))
                {
                    var oldPhotoPath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Restaurant", oldPhoto);
                    System.IO.File.Delete(oldPhotoPath);
                }

                var InputFile = HttpContext.Request.Form.Files[0];
                var InputFilePath = "";

                var UniqueId = Guid.NewGuid().ToString("D");
                var PhotoFormat = InputFile.FileName.Split(".")[1];
                editedRestaurant.PhotoPath = $"{editedRestaurant.CompanyId}_{UniqueId}.{PhotoFormat}";

                InputFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", "Restaurant", editedRestaurant.PhotoPath);
                FileStream fs = new FileStream(InputFilePath, FileMode.Create);
                InputFile.CopyTo(fs);
                fs.Close();

                query.PhotoPath = editedRestaurant.PhotoPath;
            }

            // 存取地址轉經緯度

PetsWebsite/PetsWebsite/Views/Owner/CreateClinic.cshtml
@*新增診所頁面*@
<div class="d-flex align-items-center mt-3 justify-content-center">
    <h2 class="mb-0 d-inline-block"><strong>新增診所</strong></h2>
</div>
<div class="container">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb my-2 justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="~/Owner/Index" style="text-decoration:none;">管理商品</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a>新增診所資訊</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
<section id="createClinic">
    <div class="contanier mt-4">
        <form id="ClinicForm">
            <div class="row mt-4 justify-content-center">
                <div class="col col-6">
                    <div class="row g-3 bg-light rounded mb-3">
                        <div class="col col-6 was-validated">
                            <label for="ClinicName" class="form-label">診所名稱: </label>
                            <input type="text" class="form-control is-invalid" id="ClinicName" name="ClinicName" required>
                        </div>
                        <div class="col col-3 was-validated">
                            <label for="Phone" class="form-label">連絡電話: </label>
                            <input type="text" class="form-control is-invalid" id="Phone" name="Phone" required>
                        </div>
                        <div class="col col-3 was-validated">
                            <label for="Emergency" class="form-label">是否提供急診服務: </label>
                            <select class="form-select" id="Emergency" name="Emergency" aria-label="select example" required>
                                <option value="">-- 請選擇 --</option>
                                <option value=true>是</option>
                                <option value=false>否</option>
                            </select>
                        </div>
                        <div class="col col-6 was-validated">
                            <label for="City">所在城市: </label>
                            <select class="form-select" id="City" name="City" v-on:change="cityChange" aria-label="select example" required>
                                <option value="">-- 請選擇 --</option>
                                <option value="臺北市">臺北市</option>
                                <option value="新北市">新北市</option>
                            </select>
                            <div class="invalid-feedback">請選擇所在城市</div>
                        </div>
                        <div class="col col-6 was-validated">
                            <label for="Region">所在區域: </label>
                            <select class="form-select" id="Region" name="Region" aria-label="select example" required>
                                <option value="">-- 請選擇 --</option>
                                <option v-for="item in areaList" v-bind:value="item.AreaName">{{item.AreaName}}</option>
                            </select>
                            <div class="invalid-feedback">請選擇所在區域</div>
                        </div>
                        <div class="col col-12 was-validated">
                            <label for="Address" class="form-label">診所地址: </label>
                            <input type="text" class="form-control is-invalid" id="Address" name="Address" required>
                        </div>
                        <div class="col col-12">
                            <label for="ClinicMap" class="form-label">診所googleMap網址: </label>
                            <input type="text" class="form-control" id="ClinicMap" name="ClinicMap">
                        </div>
                        <div class="col col-12">
                            <label for="Service">診所提供服務項目: </label>
                            <textarea class="form-control" id="Service" name="Service" rows="3"></textarea>
                        </div>
                        <div class="col col-12">
                            <label for="Describe">診所簡述: </label>
                            <textarea class="form-control" id="Describe" name="Describe" rows="3"></textarea>
                        </div>
                        <div class="col col-12">
                            <label class="d-block" for="Photo">圖片(大小請勿超過2MB)</label>
                            <div class="mb-3">
                                <input class="form-control" type="file" id="Photo" name="PhotoPath" onchange="previewPic(this)" accept="image/*" required>
                                <img id="pic" style="width: 30%; height: 30%" />
                            </div>
                        </div>
                        <hr class="mb-0">
                        <div class="col col-12 d-flex my-3 justify-content-center">
                            <button class="btn btn-outline-danger" type="submit">確認上傳</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<script src="~/js/CityRegion.js"></script>
@section Scripts{
    <script>
        var crtClinic = new Vue({
            data: {
                cityRegion: [],
                areaList: []
            },
            mounted: function() {
                this.cityRegion = JSON.parse(cityRegionSource);
            },
            methods: {
                cityChange: function(e) {
                    for (let index = 0; index < this.cityRegion.length; index++) {
                        if (this.cityRegion[index].CityName == e.target.value) {
                            this.areaList = this.cityRegion[index].AreaList;
                            break;
                        }
                    }
                }
            }
        }).$mount('#createClinic');
        $('#ClinicForm').submit(function(e) {
            e.preventDefault();
            var formdata = new FormData(this);
            console.log(e);
            $.ajax({
                url: "/api/ProductManageAPI/NewClinic",
                type: "POST",
                data: formdata,
                async: false,
                cache: false,
                contentType: false,
                enctype: "multipart/form-data",
                process: false,
                processData: false
            })
                .done(function(resp) {
                    console.log("resp", resp)
                    if (resp) {
                        CreateSuccess();
                    } else {
                        CreateFalse();
                    }
                })
                .fail(function(err) {
                    console.log("err", err);
                    CreateFalse();
                })
        })
        function CreateSuccess() {
            swal({
                title: '新增成功',
                type: 'success',
                closeOnClickOutside: false,
                icon: "success",
                timer: 1000,
                button: false,
            }).then(() => { window.location.href = "/Owner/Index"; });
        };
        function CreateFalse() {
            swal({
                title: '新增失敗',
                type: 'error',
                closeOnClickOutside: false,
                icon: "error",
                timer: 1000,
                button: false,
            });
        };
        // 預覽圖片
        function previewPic(e) {
            maxSize_2MB = 1 * 1024 * 1024;

            if (e.files[0].size > maxSize_2MB) {
                alert('圖片大小超過2MB！無法上傳');
                e.value = "";
            }
            else {
                pic.src = URL.createObjectURL(e.files[0])
            }
        }
    </script>
}

PetsWebsite/PetsWebsite/Views/Owner/CreateProduct.cshtml
@*新增商品頁面*@
<section id="createProduct">
    <div class="d-flex align-items-center mt-3 justify-content-center">
        <h2 class="mb-0 d-inline-block"><strong>新增商品</strong></h2>
    </div>
    <div class="container">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb my-2 justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="~/Owner/Index" style="text-decoration:none;">管理商品</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a>新增商品資訊</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="contanier">
        <form id="productForm">
            <div class="row mt-4 justify-content-center">
                <div class="col col-6">
                    <div class="row g-3 bg-light rounded mb-3">
                        <div class="col col-6 was-validated">
                            <label for="ProductName" class="form-label">商品名稱: </label>
                            <input type="text" class="form-control is-invalid" id="ProductName" name="ProductName" required>
                        </div>
                        <div class="col col-6 was-validated">
                            <label for="UnitPrice" class="form-label">商品單價: </label>
                            <input type="text" class="form-control is-invalid" id="UnitPrice" name="UnitPrice" required>
                        </div>
                        <div class="col col-4">
                            <label for="Discount">商品折扣: </label>
                            <select class="form-select" id="Discount" name="Discount" aria-label="select example" required>
                                <option value="">-- 請選擇 --</option>
                                <option value="1">無</option>
                                <option value="0.95">95 折</option>
                                <option value="0.9">9 折</option>
                                <option value="0.85">85 折</option>
                                <option value="0.8">8 折</option>
                                <option value="0.75">75 折</option>
                                <option value="0.7">7 折</option>
                                <option value="0.65">65 折</option>
                                <option value="0.6">6 折</option>
                                <option value="0.55">55 折</option>
                                <option value="0.5">5 折</option>
                                <option value="0.45">45 折</option>
                                <option value="0.4">4 折</option>
                                <option value="0.35">35 折</option>
                                <option value="0.3">3 折</option>
                                <option value="0.25">25 折</option>
                                <option value="0.2">2 折</option>
                                <option value="0.15">15 折</option>
                                <option value="0.1">1 折</option>
                            </select>
                        </div>
                        <div class="col col-4">
                            <label for="Species">商品分類: </label>
                            <select class="form-select" id="Species" name="Species" aria-label="select example" required>
                                <option value="">-- 請選擇 --</option>
                                <option value="0">犬貓</option>
                                <option value="1">非犬貓</option>
                            </select>
                        </div>
                        <div class="col col-4">
                            <label for="UnitsInStock">商品庫存: </label>
                            <input type="text" class="form-control" id="UnitsInStock" name="UnitsInStock">
                        </div>
                        <div class="col col-12">
                            <label for="Describe">商品描述: </label>
                            <textarea class="form-control" id="Describe" name="Describe" rows="3"></textarea>
                        </div>
                        <div class="col col-12">
                            <label class="d-block" for="">圖片(大小請勿超過2MB)</label>
                            <div class="mb-3">
                                <input class="form-control" type="file" id="PhotoPath" name="PhotoPath" onchange="previewPic(this)" accept="image/*" required>
                                <img id="pic" style="width: 50%; height: 50%" />
                            </div>
                        </div>
                        <hr class="mb-0">
                        <div class="col col-12 d-flex my-3 justify-content-center">
                            <button class="btn btn-outline-danger" type="submit">確認上傳</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>


@section Scripts{
    <script>
        $('#productForm').submit(function(e) {
            e.preventDefault();
            var formdata = new FormData(this);
            console.log(e);
            $.ajax({
                url: "/Owner/NewProduct",
                type: "POST",
                data: formdata,
                async: false,
                cache: false,
                contentType: false,
                enctype: "multipart/form-data",
                process: false,
                processData: false
            })
                .done(function(resp) {
                    console.log("resp", resp)
                    if (resp) {
                        swal({
                            title: '新增成功',
                            type: 'success',
                            closeOnClickOutside: false,
                            icon: "success",
                            timer: 1000,
                            button: false,
                        }).then(() => { window.location.href = "/Owner/Index"; });
                    }
                })
                .fail(function(err) {
                    console.log("err", err);
                    CreateFalse();
                })
        })
        //預覽上傳圖片
        function previewPic(e) {
            maxSize_2MB = 1 * 1024 * 1024;

            if (e.files[0].size > maxSize_2MB) {
                alert('圖片大小超過2MB！無法上傳');
                e.value = "";
            }
            else {
                pic.src = URL.createObjectURL(e.files[0]) // 讀取圖檔
            }
        }
    </script>
}

PetsWebsite/PetsWebsite/Views/Owner/EditRestaurant.cshtml
@*@model PetsWebsite.Models.Restaurant*@

@{
    var Restaurantstring = Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.editRestaurant);
}
<div class="d-flex align-items-center mt-3 justify-content-center">
    <h2 class="mb-0 d-inline-block"><strong>修改餐廳資訊</strong></h2>
</div>
<div class="container">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb my-2 justify-content-center">
                    <li class="breadcrumb-item">
                        <a href="~/Owner/Index" style="text-decoration:none;">管理商品</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a>修改餐廳資訊</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
<section id="editRestaurant">
    <div class="contanier mt-4">
        <form id="restaurantForm" action="@Url.Action("SaveEditedRestaurant","Owner")" method="post" enctype="multipart/form-data">
            <div class="row mt-4 justify-content-center">
                <div class="col col-6">
                    <div class="row g-3 bg-light rounded mb-3">
                        <div class="col col-12">
                            <label for="RestaurantId" class="form-label">餐廳ID: </label>
                            <input type="text" class="form-control" v-bind:value="editRestaurant.RestaurantId" id="RestaurantId" name="RestaurantId" readonly>
                        </div>
                        <div class="col col-6 was-validated">
                            <label for="RestaurantName" class="form-label">餐廳名稱: </label>
                            <input type="text" class="form-control is-invalid" v-bind:value="editRestaurant.RestaurantName" id="RestaurantName" name="RestaurantName" required>
                        </div>
                        <div class="col col-6 was-validated">
                            <label for="Phone" class="form-label">連絡電話: </label>
                            <input type="text" class="form-control is-invalid" v-bind:value="editRestaurant.Phone" id="Phone" name="Phone" required>
                        </div>
                        <div class="col col-6">
                            <label for="City">所在城市: </label>
                            <select class="form-select" v-on:change="changeCity" name="City" v-model="selectedCity" aria-label="select example">
                                <option value="臺北市">臺北市</option>
                                <option value="新北市">新北市</option>
                            </select>
                        </div>
                        <div class="col col-6">
                            <label for="Region">所在區域: </label>
                            <select class="form-select" v-model="selectedRegion" name="Region" aria-label="select example" required>
                                <option v-for="item in areaList" v-bind:value="item.AreaName">{{item.AreaName}}</option>
                            </select>
                        </div>
                        <div class="col col-12 was-validated">
                            <label for="Address" class="form-label">餐廳地址: </label>
                            <input type="text" class="form-control is-invalid" v-bind:value="editRestaurant.Address" id="Address" name="Address" placeholder="餐廳地址..." required>
                        </div>
                        <div class="col col-12=">
                            <label for="Reserve" class="form-label">餐廳預約網址(選填): </label>
                            <input type="text" class="form-control" v-bind:value="editRestaurant.Reserve" id="Reserve" name="Reserve">
                        </div>
                        <div class="col col-12">
                            <label for="BusyTime">餐廳營業時間: </label>
                            <textarea class="form-control" id="BusyTime" v-bind:value="editRestaurant.BusyTime" name="BusyTime" rows="3" required></textarea>
                        </div>
                        <div class="col col-12">
                            <label for="Introduction">餐廳簡述: </label>
                            <textarea class="form-control" id="Introduction" name="Introduction" rows="3">{{editRestaurant.Introduction}}</textarea>
                        </div>
                        <div class="col col-12">
                            <label class="d-block" for="Photo">圖片(大小請勿超過2MB)</label>
                            <div class="mb-3">
                                <input class="form-control" type="file" id="Photo" name="Photo" onchange="previewPic(this)" accept="image/*">
                                <img id="pic" v-bind:src="'/images/Restaurant/' + editRestaurant.PhotoPath" style="height: 30%; width: 30%;" />
                            </div>
                        </div>
                        <hr class="mb-0">
                        <div class="col col-12 d-flex my-3 justify-content-center">
                            <button class="btn btn-outline-danger" type="submit">確認修改</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<script src="~/js/CityRegion.js"></script>
<script>
    var Restaurant = @Html.Raw(Restaurantstring)
    var editRest = new Vue({
        data: {
            cityRegion: [],
            areaList: [],
            editRestaurant: Restaurant,
            selectedCity: "",
            selectedRegion: ""
        },
        mounted: function(){
            this.cityRegion = JSON.parse(cityRegionSource);
            this.selectedCity = this.editRestaurant.City;
            this.selectedRegion = this.editRestaurant.Region;
            for (let index = 0; index < this.cityRegion.length; index++) {
                if (this.cityRegion[index].CityName == this.selectedCity) {
                    this.areaList = this.cityRegion[index].AreaList;
                    break;
                }
            }
        },
        methods: {
            changeCity: function(e) {
                for (let index = 0; index < this.cityRegion.length; index++) {
                    if(this.cityRegion[index].CityName == e.target.value){
                        this.areaList = this.cityRegion[index].AreaList;
                        break;
                    }
                }
            }
        }
    }).$mount('#editRestaurant');

    function previewPic(e) {
        maxSize_2MB = 1 * 1024 * 1024;

        if (e.files[0].size > maxSize_2MB) {
            alert('圖片大小超過2MB！無法上傳');
            e.value = "";
        }
        else {
            pic.src = URL.createObjectURL(e.files[0])
        }
    }
</script>